name: Test Matrix

run-name: Deploy ${{ github.ref_name }} to ${{ (github.event_name == 'release' && 'yes') || 'no' }}

on: [push]

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["database", "service"]
        envs: ${{ fromJSON('{[\"dev\"]}') }}
    steps:
      - name: Spit it out
        run: |
          echo ${{ matrix.directory }} ${{ matrix.envs }}
